version: "3.9"
services:

    # nginx
    nginx-service:
        build:
            context: docker/nginx
            dockerfile: Dockerfile
        container_name: p4-web
        ports:
            - "10081:80"
            #- "10443:443"
        volumes:
            - ./project:/var/www/html
            - ./project/storage/logs/nginx:/var/log/nginx:delegated
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:cached
            - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled:cached
            - ./docker/nginx/snippets:/etc/nginx/snippets:cached
            - ./docker/nginx/templates:/etc/nginx/templates:cached
        env_file:
            - .nginx.env
        depends_on:
            - app-service
            - composer-service
            - mariadb-service
        networks:
            - backend

    # composer
    composer-service:
        image: composer/composer:latest
        #image: arm64v8/composer:2.2
        container_name: p4-comp
        volumes:
            - ./project:/app
        working_dir: /app
        command: install --ignore-platform-reqs --no-scripts
        networks:
            - backend

    # php
    app-service:
        build:
            context: docker
            dockerfile: php/Dockerfile
        container_name: p4-app
        env_file:
            - .php.env
        ports:
            - "9000:9000"
            - "8000:8000" # phalcon webtools as a php webserver
        volumes:
            - ./project:/var/www/html:cached
            - ~/composer:/root/.composer
        networks:
            - backend

    # mysql (mariadb)
    mariadb-service:
        image: mariadb:latest
        container_name: p4-mariadb
        ports:
            - "3307:3306"
        volumes:
            - ./docker/mysql/cnf:/etc/mysql/conf.d
            - ./docker/mysql/database:/var/lib/mysql
            - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        restart: always
        env_file:
            - .sql.env
        networks:
            - backend

networks:
    backend:
